### ISSUE TITLE
Transc.: misc.

### ISSUE THREAD

**Issue by BOberreither** [karl-kraus/wpn-static#83]
- [x] p. 10: This element: `<metamark function="printInstruction" change="#pencilOnProof" rend="marginRight" corresp="#metam0010_01">&#10003;</metamark>` is placed inline, should be in the margin. **>** see #32 update
- [x] p. 55 and others: `<l style="indent1">` is much too far on the right; **>** try 7.2rem for indent1; indent3 seems to be ok.
- [x] strange one: [p 75](https://karl-kraus.github.io/wpn-static/idPb0075.html), funny placement of "Mit der Generalstabskarte in der "
- [x] [p 78](https://karl-kraus.github.io/wpn-static/idPb0078.html) handwritten metamark displayed as part of printed text paragraph **>** see updated #32 
- [x] [p 142](https://karl-kraus.github.io/wpn-static/idPb0142.html) - note contains an `add @rend="below"`, is not displayed. > see updated #32

**Comment by linxOD** [comment]
> p. 10
Is there a gernal rule how to handle `metamark` ? According to #32 there are no rules yet how to handle `metamark function=printInstruction` therefore it is simply rendered at inline location.

**Comment by linxOD** [comment]
> p. 55

looks like there is extra word-spacing for `longQuoteVerse` l . 
I tried 0.2rem word-spacing and 8rem for indent1. Which comes quite close.
